[build-system]
requires = ["setuptools >= 60.0"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">= 3.6"
name = "Swish"
description = "Swish activation function"
dynamic = ["version"]